import fs from "node:fs";
import path from "node:path";
import {
  buildManifestFromOpenApiText,
  extractOpenApiInfoFromText,
  slugifyManifestName,
} from "@xapps-platform/openapi-import";

type CliArgValue = string | boolean | string[];
type CliArgs = Record<string, CliArgValue>;

type ParsedManifest = {
  slug: string;
  tools: Array<{
    tool_name: string;
    input_schema: unknown;
    output_schema: unknown;
  }>;
  widgets: Array<unknown>;
};

type ManifestDeps = {
  argString: (args: CliArgs, ...keys: string[]) => string | undefined;
  argFlag: (args: CliArgs, key: string) => boolean;
  readInput: (from: string, fetchTimeoutMs: number) => Promise<string>;
  parsePositiveIntOrThrow: (value: string | undefined, fallback: number, label: string) => number;
  parseManifestFromFile: (from: string) => { manifest: ParsedManifest; filePath: string };
  readJsonFile: (file: string) => unknown;
};

type ContractVector = {
  name?: string;
  tool_name?: string;
  input?: unknown;
  expected_output?: unknown;
};

type ContractVectorSet = {
  vectors?: ContractVector[];
};

function buildInitManifestTemplate(input: {
  name: string;
  slug: string;
  version: string;
}): Record<string, unknown> {
  return {
    name: input.name,
    slug: input.slug,
    version: input.version,
    target_client_id: "REPLACE_CLIENT_ID",
    description: "Generated by xapps init",
    tools: [
      {
        tool_name: "example_tool",
        title: "Example Tool",
        input_schema: {
          type: "object",
          properties: {
            message: { type: "string" },
          },
          required: ["message"],
        },
        output_schema: {
          type: "object",
          properties: {
            echoed: { type: "string" },
          },
        },
      },
    ],
    widgets: [
      {
        widget_name: "example_widget",
        type: "write",
        renderer: "json-forms",
        bind_tool_name: "example_tool",
        entry: {
          kind: "platform_template",
          template: "write_form",
        },
      },
    ],
  };
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return !!value && typeof value === "object" && !Array.isArray(value);
}

function jsonTypeMatches(type: string, value: unknown): boolean {
  if (type === "string") return typeof value === "string";
  if (type === "number") return typeof value === "number";
  if (type === "integer") return typeof value === "number" && Number.isInteger(value);
  if (type === "boolean") return typeof value === "boolean";
  if (type === "array") return Array.isArray(value);
  if (type === "object") return isPlainObject(value);
  if (type === "null") return value === null;
  return true;
}

function validatePayloadAgainstSchema(schema: unknown, payload: unknown, label: string): string[] {
  if (!isPlainObject(schema)) return [];
  if (!isPlainObject(payload)) {
    return [`${label} must be a JSON object`];
  }

  const errors: string[] = [];
  const required = Array.isArray(schema.required) ? schema.required : [];
  for (const key of required) {
    if (typeof key === "string" && !(key in payload)) {
      errors.push(`${label} missing required field: ${key}`);
    }
  }

  const properties = isPlainObject(schema.properties) ? schema.properties : {};
  for (const [key, propSchema] of Object.entries(properties)) {
    if (!(key in payload)) continue;
    if (!isPlainObject(propSchema)) continue;
    const expectedType = typeof propSchema.type === "string" ? propSchema.type : "";
    if (expectedType && !jsonTypeMatches(expectedType, payload[key])) {
      errors.push(
        `${label}.${key} type mismatch (expected ${expectedType}, got ${Array.isArray(payload[key]) ? "array" : typeof payload[key]})`,
      );
    }
  }

  return errors;
}

export async function runImportCommand(args: CliArgs, deps: ManifestDeps) {
  const from = deps.argString(args, "from");
  const out = deps.argString(args, "out");
  const fetchTimeoutMs = deps.parsePositiveIntOrThrow(
    deps.argString(args, "fetch-timeout-ms"),
    10000,
    "--fetch-timeout-ms",
  );
  if (!from || !out) {
    throw new Error("Missing required arguments: --from and --out");
  }

  const openApiText = await deps.readInput(from, fetchTimeoutMs);
  const fallbackInfo = extractOpenApiInfoFromText(openApiText);
  const name = deps.argString(args, "name") || fallbackInfo.title || "OpenAPI Imported App";
  const slug = deps.argString(args, "slug") || slugifyManifestName(name) || "openapi-imported-app";

  const manifest = buildManifestFromOpenApiText(openApiText, {
    name,
    slug,
    version: deps.argString(args, "version") || "1.0.0",
    description: deps.argString(args, "description") || fallbackInfo.description,
    endpointBaseUrl: deps.argString(args, "endpoint") || "https://api.example.com",
    endpointEnv: deps.argString(args, "endpoint-env") || "prod",
  });

  const outPath = path.resolve(process.cwd(), out);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, JSON.stringify(manifest, null, 2));
  console.log(
    `Manifest generated: ${outPath}\nTools: ${manifest.tools.length}\nWidgets: ${manifest.widgets.length}`,
  );
}

export function runValidateCommand(args: CliArgs, deps: ManifestDeps) {
  const from = deps.argString(args, "from");
  if (!from) {
    throw new Error("Missing required argument: --from <manifest.json>");
  }

  const { manifest, filePath } = deps.parseManifestFromFile(from);
  console.log(
    `Manifest valid: ${filePath}\nSlug: ${manifest.slug}\nTools: ${manifest.tools.length}\nWidgets: ${manifest.widgets.length}`,
  );
}

export function runInitCommand(args: CliArgs, deps: ManifestDeps) {
  const out = deps.argString(args, "out");
  if (!out) {
    throw new Error("Missing required argument: --out <directory>");
  }

  const outDir = path.resolve(process.cwd(), out);
  fs.mkdirSync(outDir, { recursive: true });

  const name = deps.argString(args, "name") || "My Xapp";
  const slug = deps.argString(args, "slug") || slugifyManifestName(name) || "my-xapp";
  const version = deps.argString(args, "version") || "1.0.0";
  const force = deps.argFlag(args, "force");

  const manifestPath = path.join(outDir, "manifest.json");
  const readmePath = path.join(outDir, "README.md");

  if (!force) {
    for (const filePath of [manifestPath, readmePath]) {
      if (fs.existsSync(filePath)) {
        throw new Error(`File already exists: ${filePath} (use --force to overwrite)`);
      }
    }
  }

  const manifest = buildInitManifestTemplate({ name, slug, version });
  fs.writeFileSync(manifestPath, JSON.stringify(manifest, null, 2));
  fs.writeFileSync(
    readmePath,
    `# ${name}\n\nGenerated by xapps init.\n\nNext steps:\n\n1. Edit manifest.json (set target_client_id to the tenant client ID)\n2. Validate: xapps validate --from manifest.json\n3. Import/OpenAPI: xapps import ...\n`,
  );

  console.log(`Initialized xapp scaffold in: ${outDir}`);
}

export function runTestCommand(args: CliArgs, deps: ManifestDeps) {
  const from = deps.argString(args, "from");
  const vectorsPath = deps.argString(args, "vectors");
  if (!from || !vectorsPath) {
    throw new Error(
      "Missing required arguments: --from <manifest.json> and --vectors <vectors.json>",
    );
  }

  const { manifest, filePath: manifestPath } = deps.parseManifestFromFile(from);
  const vectorsRaw = deps.readJsonFile(vectorsPath);
  if (!isPlainObject(vectorsRaw)) {
    throw new Error("Vector file must be a JSON object with a vectors[] field");
  }
  const vectorsContainer = vectorsRaw as ContractVectorSet;
  if (!Array.isArray(vectorsContainer.vectors)) {
    throw new Error("Vector file must contain vectors[]");
  }

  const failures: string[] = [];
  for (let index = 0; index < vectorsContainer.vectors.length; index += 1) {
    const vector = vectorsContainer.vectors[index];
    const name = typeof vector?.name === "string" ? vector.name : `vector_${index + 1}`;
    const toolName = typeof vector?.tool_name === "string" ? vector.tool_name : "";
    if (!toolName) {
      failures.push(`${name}: missing tool_name`);
      continue;
    }
    const tool = manifest.tools.find((item) => item.tool_name === toolName);
    if (!tool) {
      failures.push(`${name}: unknown tool_name '${toolName}'`);
      continue;
    }

    const inputErrors = validatePayloadAgainstSchema(
      tool.input_schema,
      vector.input || {},
      "input",
    );
    const outputErrors = validatePayloadAgainstSchema(
      tool.output_schema,
      vector.expected_output || {},
      "expected_output",
    );
    for (const error of [...inputErrors, ...outputErrors]) {
      failures.push(`${name}: ${error}`);
    }
  }

  if (failures.length) {
    throw new Error(
      `Contract test failed (${failures.length} issues)\n${failures.map((f) => `- ${f}`).join("\n")}`,
    );
  }

  console.log(
    `Contract test passed: ${vectorsContainer.vectors.length} vector(s)\nManifest: ${manifestPath}\nVectors: ${path.resolve(process.cwd(), vectorsPath)}`,
  );
}
